name = "pujangga"
license = "MIT"
licenselink = "https://github.com/nikolasdion/pujangga-hugo-theme/blob/master/LICENSE.md"
description = "Minimal Hugo theme for poetry."
homepage = "https://github.com/nikolasdion/pujangga-hugo-theme"
tags = [
  "blog",
  "minimal",
  "monospace",
  "dark mode",
  "simple",
  "clean",
  "light",
  "responsive",
  "fast",
  "no-js",
  "no-tracking",
  "privacy",
]
features = ["blog", "privacy", "responsive", "fast"]
min_version = "0.1.0"

[author]
name="nikolasdion"
homepage = "https://github.com/nikolasdion"

[original]
author = "morph"
homepage = "https://morph.sh"
repo = "https://github.com/colorchestra/smol"
